export const ERROR_CODES = {
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  PERSON_NOT_FOUND: 'PERSON_NOT_FOUND',
  
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_CPF: 'INVALID_CPF',
  INVALID_EMAIL: 'INVALID_EMAIL',
  REQUIRED_FIELD: 'REQUIRED_FIELD',
  
  CONFLICT_ERROR: 'CONFLICT_ERROR',
  PERSON_ALREADY_EXISTS: 'PERSON_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];

